# Generated by Django 3.2 on 2023-02-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20230226_1002'),
        ('reviews', '0009_auto_20230226_1046'),
    ]

    operations = [
    ]
